### ISSUE TITLE
Looks for FFTW when Kokkos::Threads is enabled

### ISSUE THREAD

**Issue by lucbv** [CExA-project/kokkos-fft#31]
It would be nice to modify the config to include the use case of Kokkos::Threads, it works fine and is actually used commonly on MacOS since OpenMP is not available by default.

**Comment by yasahi-hpc** [comment]
That is true. Sorry, but I focused on CUDA, HIP, SYCL and OpenMP backend only. I will fix the CMake soon. 
In order to fully support Threads backend, I will add some tests which will be made in the future.
