### ISSUE TITLE
Kokkos version check

### ISSUE THREAD

**Issue by lucbv** [CExA-project/kokkos-fft#32]
Hi all another issue appears to be the lack of check on the Kokkos Version being used when building against a pre-installed Kokkos library.
I am suspecting that for the time being it works with 4.2.0 and maybe up to 4.0.0 but likely not against anything older than that?
It would be good to add something in CMakeLists.txt to warn users if they attempt to install against an unsupported version.
Also updating the documentation to reflect what is actually supported would be great!

**Comment by cedricchevalier19** [comment]
You can put a minimal version with `find_package`.

**Comment by yasahi-hpc** [comment]
In addition, I would improve the Versioning in CMake which is added in (#41).
