### ISSUE TITLE
Pre-build Kokkos on CI

### ISSUE THREAD

**Issue by pzehner** [CExA-project/kokkos-fft#43]
Build and install Kokkos on Release mode in the images.

Kokkos would be discovered as an installed library, backend parameters should be deduced and not passed again.

The test example build at the end of the workflow should properly use this installed version of Kokkos.

Optionally, `KokkosFFT_INTERNAL_Kokkos` should be removed.

**Comment by pzehner** [comment]
If Kokkos is build and installed in the image, that means we not only enforce the backend (which is expected), but also the architecture (which is unknown at this stage). This may cause troubles for the PThread backend support (which has the same building environment as OpenMP).

**Comment by yasahi-hpc** [comment]
I am not sure about the second point. I thought we specify a latest architecture for GPU and do not specify anything for CPU backends. 

As for the first point, we may need to install Kokkos on separate locations for each backend. If we would like to reuse the OpenMP container
